# These are the youtube video to downloaded. Videos are under 4 minutes. These are essentially tutorial videos.

video_url = {
    "https://www.youtube.com/watch?v=7395LUP9dsk": "excel",
    "https://www.youtube.com/watch?v=I-waFp6rLc0": "copilot",
    "https://www.youtube.com/watch?v=9dpWnaMYoC4": "android",
    "https://www.youtube.com/watch?v=2GkQRmXiHlE&list=PL_dhPga7ruucgAuE5um_jnuSaljJJ4O0D&index=2": "windows 10",
    "https://www.youtube.com/watch?v=hUzYLQ30qFY&list=PL_dhPga7ruucgAuE5um_jnuSaljJJ4O0D&index=4": "windows 10",
    "https://www.youtube.com/watch?v=AB3ozEQj4e0&list=PL_dhPga7ruucgAuE5um_jnuSaljJJ4O0D&index=7": "windows 10",
    "https://www.youtube.com/watch?v=p7aKf_3TMMo&list=PL_dhPga7ruucgAuE5um_jnuSaljJJ4O0D&index=23": "windows 10",
    "https://www.youtube.com/watch?v=5Fcf-8LPvws": "linux",
    "https://www.youtube.com/watch?v=DpdmUmglPBA": "linux",
    "https://www.youtube.com/watch?v=zLL8US4EdCo&pp=ygUObGludXggdHV0b3JpYWw%3D": "linux",
    "https://www.youtube.com/watch?v=-wRYpGkwXZg": "word",
    "https://www.youtube.com/watch?v=xLcrKMAEnOw": "word",
    "https://www.youtube.com/watch?v=JIOaLKsz2R0": "google workspace",
    "https://www.youtube.com/watch?v=VqTjJubt0kE": "google workspace",
    "https://www.youtube.com/watch?v=MuV7jMaoVsA": "google docs",
    "https://www.youtube.com/watch?v=YcSzio__y64": "google docs",
    "https://www.youtube.com/watch?v=167iJqOKXiI": "google docs",
    "https://www.youtube.com/watch?v=uIwYGviYuVM": "google docs",
    "https://www.youtube.com/watch?v=6KnBebEr1Nw": "libreoffice",
    "https://www.youtube.com/watch?v=2Go4MO_fWf8": "libreoffice",
    "https://www.youtube.com/watch?v=BEa5YBhq2xI": "libreoffice",
    "https://www.youtube.com/watch?v=-eKjjKcPZzI": "vlc",
    "https://www.youtube.com/watch?v=-MgYbxYzFW4": "vlc",
    "https://www.youtube.com/watch?v=zZZpKUaJK-g": "vlc",
    "https://www.youtube.com/watch?v=qgRvUK8bxGU": "vlc",
    "https://www.youtube.com/watch?v=KzlckAqtfWM": "spotify",
    "https://www.youtube.com/watch?v=c7cn-Wc-FfM": "spotify",
    "https://www.youtube.com/watch?v=bb0PvAOByEo": "apple music",
    "https://www.youtube.com/watch?v=2tK6CbnG0Oc": "photoshop",
    "https://www.youtube.com/watch?v=wot8RMrSrp0": "photoshop",
    "https://www.youtube.com/watch?v=4Cl9kw9K-kk": "photoshop",
    "https://www.youtube.com/watch?v=chr6OnE-wFg": "photoshop",
    "https://www.youtube.com/watch?v=eBSMwpy2Hqg": "slack",
    "https://www.youtube.com/watch?v=6L-U6EcPS9w": "slack",
    "https://www.youtube.com/watch?v=cJ9q3l1gQ-g": "slack",
    "https://www.youtube.com/watch?v=jMDiadwZeD8": "slack",
    "https://www.youtube.com/watch?v=3F3HcegaW28": "zoom",
    "https://www.youtube.com/watch?v=r9bomXarDJI": "vscode",
    "https://www.youtube.com/watch?v=fEp5nWvujhI": "vscode",
}
